// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLittleBank.Dal;

namespace MyLittleBank.Api.Migrations
{
    [DbContext(typeof(MyLittleBankDbContext))]
    [Migration("20181011054500_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyLittleBank.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<bool>("IsLocked");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new { Id = 1, Balance = 102.45m, IsLocked = false, Number = "PBO1221323" },
                        new { Id = 2, Balance = 10002.98m, IsLocked = false, Number = "PIC9984567" },
                        new { Id = 3, Balance = 677.71m, IsLocked = true, Number = "PAC0784412" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
