//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLittleBank.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLittleBank.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot operate with a locked account.
        /// </summary>
        internal static string exception_AccountIsLocked {
            get {
                return ResourceManager.GetString("exception_AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Charge to a Bank Account because it is locked or balance is not greater than amount to charge..
        /// </summary>
        internal static string exception_InvalidAccountToBeCharged {
            get {
                return ResourceManager.GetString("exception_InvalidAccountToBeCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument format is not valid.
        /// </summary>
        internal static string exception_InvalidArgument {
            get {
                return ResourceManager.GetString("exception_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Id.
        /// </summary>
        internal static string field_BankAccountId {
            get {
                return ResourceManager.GetString("field_BankAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Balance.
        /// </summary>
        internal static string field_BankBalance {
            get {
                return ResourceManager.GetString("field_BankBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} cannot be null..
        /// </summary>
        internal static string message_FieldCannotBeNull {
            get {
                return ResourceManager.GetString("message_FieldCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be equal to {1}..
        /// </summary>
        internal static string message_FieldMustBeEqualTo {
            get {
                return ResourceManager.GetString("message_FieldMustBeEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string message_FieldMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("message_FieldMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
    }
}
